import Foundation
import Security

// Kept outside the Swift package so an ordinary app rebuild does not rebuild this helper.
struct Request: Decodable {
    let operation: String
    let account: String
    let value: String?
    let allowInteraction: Bool
}
struct Response: Encodable {
    let status: OSStatus
    var value: String? = nil
}

func reply(_ response: Response) -> Never {
    if let data = try? JSONEncoder().encode(response) {
        FileHandle.standardOutput.write(data)
    }
    exit(response.status == errSecSuccess ? 0 : 1)
}

func verifyParent() -> Bool {
    // The certificate fingerprint is generated by the build script, not accepted from stdin/env.
    let text = "identifier \"com.local.AICredits\" and certificate leaf = H\"\(SigningIdentity.fingerprint)\""
    var requirement: SecRequirement?
    guard SecRequirementCreateWithString(text as CFString, [], &requirement) == errSecSuccess else { return false }
    var parent: SecCode?
    let attributes = [kSecGuestAttributePid as String: getppid()] as CFDictionary
    guard SecCodeCopyGuestWithAttributes(nil, attributes, [], &parent) == errSecSuccess,
          let parent else { return false }
    return SecCodeCheckValidity(parent, [], requirement) == errSecSuccess
}

guard verifyParent() else { reply(Response(status: errSecAuthFailed)) }
// The app uses private pipes, never command-line arguments, to transfer credentials.
let input = FileHandle.standardInput.readDataToEndOfFile()
guard input.count <= 1_048_576,
      let request = try? JSONDecoder().decode(Request.self, from: input),
      ["OpenAI", "Claude", "Gemini", "ElevenLabs", "SigningProbe"].contains(request.account),
      ["get", "set", "delete"].contains(request.operation) else {
    reply(Response(status: errSecParam))
}

// File-based login keychains do not consistently honor LAContext.interactionNotAllowed.
// This setting is confined to this short-lived helper process, not the main app.
let interaction = SecKeychainSetUserInteractionAllowed(request.allowInteraction)
guard interaction == errSecSuccess else { reply(Response(status: interaction)) }
let base: [String: Any] = [
    kSecClass as String: kSecClassGenericPassword,
    kSecAttrService as String: "com.local.AICredits.credentials.v2",
    kSecAttrAccount as String: request.account
]

switch request.operation {
case "get":
    var query = base
    query[kSecReturnData as String] = true
    query[kSecMatchLimit as String] = kSecMatchLimitOne
    var item: CFTypeRef?
    let status = SecItemCopyMatching(query as CFDictionary, &item)
    if status == errSecItemNotFound { reply(Response(status: errSecSuccess)) }
    guard status == errSecSuccess else { reply(Response(status: status)) }
    guard let data = item as? Data, let value = String(data: data, encoding: .utf8) else {
        reply(Response(status: errSecDecode))
    }
    reply(Response(status: errSecSuccess, value: value))
case "set":
    guard let value = request.value else { reply(Response(status: errSecParam)) }
    let attributes = [kSecValueData as String: Data(value.utf8)]
    let status = SecItemUpdate(base as CFDictionary, attributes as CFDictionary)
    guard status == errSecItemNotFound else { reply(Response(status: status)) }
    var query = base
    query[kSecValueData as String] = Data(value.utf8)
    query[kSecAttrLabel as String] = "AI Credits · \(request.account)"
    reply(Response(status: SecItemAdd(query as CFDictionary, nil)))
case "delete":
    let status = SecItemDelete(base as CFDictionary)
    reply(Response(status: status == errSecItemNotFound ? errSecSuccess : status))
default:
    reply(Response(status: errSecParam))
}
